### ISSUE TITLE
load error occur - http://apache.org/xml/features/disallow-doctype-decl" set to true

### ISSUE THREAD

**Issue by kyungminiyang** [fzilic/Grails-MyBatis#7]
I use Grails-2.3.7 & mybatis:0.0.2 plugin 

when i run-app, error occur 
2014-05-20 18:57:06,500 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE은 "http://apache.org/xml/features/disallow-doctype-decl" 기능이 true로 설정된 경우 허용되지 않습니다.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at org.grails.plugins.mybatis.MappingSupport.loadMappingFile(MappingSupport.groovy:143)
	at org.grails.plugins.mybatis.MappingSupport.registerMappings(MappingSupport.groovy:70)
	at MybatisGrailsPlugin$_closure3_closure17.doCall(MybatisGrailsPlugin.groovy:141)
	at MybatisGrailsPlugin$_closure3.doCall(MybatisGrailsPlugin.groovy:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

so i modify plugin source 
org.grails.plugins.mybatis.MappingSupport.groovy
private loadMappingFile(String filename, GrailsClass grailsClass, boolean validating = true) {
               ....

		XmlSlurper xmlSlurper = new XmlSlurper(validating, true)
		xmlSlurper.entityResolver = resolver as EntityResolver
		xmlSlurper.setFeature("http://apache.org/xml/features/disallow-doctype-decl", false)   // <== add here
		return xmlSlurper.parseText(mappingFileText)
}

then, 
grails run anyway... 
plus this issue only in jdk1.7  (jdk1.6 is no error)

can you tell me why "http://apache.org/xml/features/disallow-doctype-decl" set to false?
or  other method can not modify plugin code

**Comment by fzilic** [comment]
Thanks to effort by alcidesfp it works right now, and it should still work on Grails 2.0.x.
